fix(openresty): compilation failure due to missing netfilter headers
The base build environment lacks these Linux kernel headers, causing the compiler to fail when resolving netfilter definitions.

394.5 	../ngx_stream_lua-0.0.17/src/ngx_stream_lua_api.c
394.7 ../ngx_stream_lua-0.0.17/src/ngx_stream_lua_api.c:21:10: fatal error: linux/netfilter_ipv4.h: No such file or directory
394.7    21 | #include <linux/netfilter_ipv4.h>
394.7       |          ^~~~~~~~~~~~~~~~~~~~~~~~
394.7 compilation terminated.
394.8 make[2]: *** [objs/Makefile:2802: objs/addon/src/ngx_stream_lua_api.o] Error 1
394.8 make[2]: Leaving directory '/tmp/openresty-1.29.4.1/build/nginx-1.29.4'
394.8 make[1]: *** [Makefile:10: build] Error 2
394.8 make[1]: Leaving directory '/tmp/openresty-1.29.4.1/build/nginx-1.29.4'
394.8 make: *** [Makefile:11: all] Error 2

Signed-off-by: honeok <i@honeok.com>