fix: add packages required for the build
169.7 ../ngx_stream_lua-0.0.18RC2/src/ngx_stream_lua_api.c:21:10: fatal error: linux/if.h: No such file or directory

Signed-off-by: honeok <i@honeok.com>